services:
  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=teste123

  app:
    image: nicolaspimentel/django-ft
    ports:
      - 8080:8080
    environment:
        - DB_HOST=db
        - DB_NAME=postgres
        - DB_USER=postgres
        - DB_PORT=5432
        - DB_PASSWORD=teste123
    command: >
      sh -c  "python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8080"
    depends_on:
      - db